apiVersion: v1
kind: LimitRange
metadata:
    name: low-resource-range
spec:
    limits:
    - default:
        cpu: 1
        memory: 500 Mi
      defaultRequest:
        cpu: 0.5
        memory: 100Mi
      type: Container
