kind: RoleBinding
apiVersion: rbac.authorization.k8s.io/v1
metadata:
  name: production-role-binding
  namespace: production
subjects:
- kind: User
  name: rwetzelberger
  apiGroup: ""
roleRef:
  kind: Role
  name: dev-prod
  apiGroup: ""
