apiVersion: v1
kind: PersistentVolume
metadata: 
  name: pvvol-1
spec:
  capacity:
    storage: 1Gi
  accessModes:
    - ReadWriteMany
  persistentVolumeReclaimPolicy: Recycle
  nfs:
    path: /opt/sfw
    server: 127.0.0.1
    readOnly: false
